# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mysite.mycity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_post', models.ImageField(blank=True, null=True, upload_to=mysite.mycity.models.post_img_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media_file', models.ManyToManyField(to='mycity.MediaFile')),
            ],
        ),
        migrations.CreateModel(
            name='PostTypeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_types', models.IntegerField(choices=[(1, 'Utilidade Pública'), (2, 'Humor'), (3, 'Política'), (4, 'Segurança'), (5, 'Saúde'), (6, 'Educação'), (7, 'Variados')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Brasil', max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('img_usr', models.ImageField(blank=True, default='pic_profile.jpg', null=True, upload_to=mysite.mycity.models.usr_img_filename)),
                ('validation_key', models.CharField(blank=True, max_length=50, null=True)),
                ('key_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_types', models.ManyToManyField(to='mycity.PostTypeUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coment',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycity.Post'),
        ),
        migrations.AddField(
            model_name='coment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
